source 'https://rubygems.org'

gem 'sinatra'
gem 'shotgun'
gem 'feedjira'
gem 'nokogiri'
gem 'ruby-readability'
gem 'curb'
gem 'json'
gem 'slim'
gem 'coffee-script'
gem 'stylus'
gem 'autoprefixer-rails'
